emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    file-type: "json"
    output-file: "openapi.admin.json"
    emitter-output-dir: "{project-root}/../tsp-output/schema"
    openapi-versions:
      - 3.1.0
